### PR TITLE
pass props down to the wrapped component

### LINKED ISSUE #1: component wrapped with provide ignores other props
There doesn't seem to be a way to pass both store and other props to the element wrapped with `provide`. It just ignores all passed in props aside from the store.

### PR DESCRIPTION
**Pull request by simpixelated**
Should fix #1.

### CODE REVIEW

**Comment by flipjs** [comment]
Hi @simpixelated ! Thanks for your help and your pull request. Could you do one more thing for me please. Currently, the build is failing, due to object spread operator cannot be transpiled. Babel needs `babel-preset-stage-0` library to convert to ES5 and save to `/lib/index.js`, which is what being published in npm.

``` diff
- "build": "babel --presets es2015 -d lib/ src/",
+ "build": "babel --presets es2015,stage-0 -d lib/ src/",
```

Or, you could use `Object.assign`, and there is no need for additional library such as `babel-preset-stage-0`:

``` diff
- (props) => React.createElement(Component, { ...store, ...props })
+ (props) => React.createElement(Component, Object.assign({}, store, props))
```

Either way, I am fine with it. If you could update the code, run `npm run build` to check if passing, then I can merge it.

Let me know if you need something more from me. I really appreciate your contribution. Oh, and please don't forget to update the README and add your name under **Contributors**. Many thanks.

Cheers!

**Comment by flipjs** [comment]
@simpixelated Oh, and one more thing. Could you please use `npm run commit` and choose **fix** and then your commit message. Or with normal `git commit` command with this commit message:

```
fix(provide): pass props down to the wrapped component

Closes #1
```

That should automatically close issue #1. The _fix_ in commit message will automatically publish this to NPM when merged.

Thanks again.

**Comment by simpixelated** [comment]
Thanks for the suggestions! I will update the PR today or tomorrow.

**Comment by flipjs** [comment]
@simpixelated Cool! If you are getting errors with `npm run build`, just let me know. I can just merge this PR, and do rest to update the npm. But I'm sure once you update your `patch-1` branch and commit, the Travis CI will turn green. :) Thanks again.

**Comment by simpixelated** [comment]
@flipjs updated!

**Comment by flipjs** [comment]
@simpixelated It's been merged! Many thanks for the bugfix. Much appreciated! 🍺

**Pull request merged**
